### ISSUE TITLE
UI stucks in processing...

### ISSUE THREAD

**Issue by udiedrichsen** [chasebank87/mesh-ai#1]
Hi,

I really love this plugin and fabric. Thanks for creating this!

I cloned today this repo installed the plugin manually. I tried to summary a youtube link. 
Works great, but the UI sticks in processing...

![image](https://github.com/user-attachments/assets/f07d05d9-5c48-430b-a99d-f1b82248c9ad)

In the debug log is the last output:
Creating output file...

I found also some other minor issues. Should I open more issues?

**Comment by chasebank87** [comment]
version 1.0.5 is the one you want to use if you are using BRAT
