### ISSUE TITLE
Pattern Not Found 

### ISSUE THREAD

**Issue by zackwenthe** [chasebank87/mesh-ai#10]
<img width="283" alt="Screenshot 2024-09-17 at 3 30 30 PM" src="https://github.com/user-attachments/assets/c9c2f571-8726-4ea1-97c4-71524c0dcc38">

The extract ideas pattern is downloaded and in my folder. I was able to successfully find it within the UI. I tried multiple items to no effect. Using BRAT and the 1.1 main branch

**Comment by chasebank87** [comment]
The plugin has officially been released in the community repo. Try to install from there and let me know if you have the issue. When you open the folder where fabric patterns are downloaded to do you see all the patterns?Sent from my iPhoneOn Sep 17, 2024, at 4:33 PM, zackwenthe ***@***.***> wrote:﻿
Screenshot.2024-09-17.at.3.30.30.PM.png (view on web)
The extract ideas pattern is downloaded and in my folder. I was able to successfully find it within the UI. I tried multiple items to no effect. Using BRAT and the 1.1 main branch

**Comment by zackwenthe** [comment]
I've updated to the community version 1.1.2 and run the patterns again with the same output. I even deleted the entire folder, and redownloaded the patterns and I get the same error
<img width="228" alt="Screenshot 2024-09-17 at 4 04 53 PM" src="https://github.com/user-attachments/assets/3a57829d-5a67-4503-97c1-6cabe86ef0f1">

**Comment by chasebank87** [comment]
Can you turn on debugging from the plugin settings, then open developer tools and copy any logs when you run the process?

When in the plugin and search for patterns does it come up? I just tried with the same pattern and it works.. I’ll need all the debug logs, turn on debugging and copy the console log from developer tools.

Also is it just that one pattern? Also take a screenshot of your settings.

**Comment by zackwenthe** [comment]
I completely removed the plugin and reinstalled, res-etup all the patterns and it seems to work now. I was able to search for the pattern and see it but it was failing to use it for some reason. 

OpenAI works and looking forward to seeing Claude and Gemini working in the future
