### ISSUE TITLE
Can we add Openrouter as the LLM API Source?

### ISSUE THREAD

**Issue by chenyuz3** [chasebank87/mesh-ai#11]
As a heavy openrouter user I find it very useful as it is much easier for users to switch between models. And it is OpenAI API compatible so shouldn't be too much of a problem to add it.

**Comment by chasebank87** [comment]
I’ll look into it and get back to you. We can leave this open.Sent from my iPhoneOn Sep 19, 2024, at 12:39 AM, chenyuz3 ***@***.***> wrote:﻿
As a heavy openrouter user I find it very useful as it is much easier for users to switch between models. And it is OpenAI API compatible so shouldn't be too much of a problem to add it.
