### ISSUE TITLE
Sidebar UX Responsive Issues

### ISSUE THREAD

**Issue by zackwenthe** [chasebank87/mesh-ai#12]
<img width="1148" alt="Screenshot 2024-09-19 at 11 07 54 AM" src="https://github.com/user-attachments/assets/64e28c54-8872-4fbe-b519-859bb20981ea">
<img width="1142" alt="Screenshot 2024-09-19 at 11 08 00 AM" src="https://github.com/user-attachments/assets/3eeef111-d02f-4709-8d20-c87141855f36">
<img width="809" alt="Screenshot 2024-09-19 at 11 08 14 AM" src="https://github.com/user-attachments/assets/031d427b-975f-4bc6-bc89-d52b043bbdb0">

Depending on the size of the sidebar width the input selectors are having overflow issues relative to the selector. And if it's small enough Tavily disappears completely. 

This is more of an issue when working on my Macbook Pro 14 screen versus a larger external monitor.

**Comment by chasebank87** [comment]
Ok I will make it more dynamic, I’ll keep this open till I have an update.Sent from my iPhoneOn Sep 19, 2024, at 12:11 PM, zackwenthe ***@***.***> wrote:﻿
Screenshot.2024-09-19.at.11.07.54.AM.png (view on web)
Screenshot.2024-09-19.at.11.08.00.AM.png (view on web)
Screenshot.2024-09-19.at.11.08.14.AM.png (view on web)
Depending on the size of the sidebar width the input selectors are having overflow issues relative to the selector. And if it's small enough Tavily disappears completely.
This is more of an issue when working on my Macbook Pro 14 screen versus a larger external monitor.
