### ISSUE TITLE
Azure deployed model fails with error net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by wally-kroeker** [chasebank87/mesh-ai#18]
I am actively using Azure models with other projects, including in production at my work so I know the deployment is setup right.  

When I try it with mesh-ai it fails with the error below. 

Error: LLM Request failed: Failed to generate
response: net::ERR_NAME_NOT_RESOLVED

I have a number of models under the same azure endpoint and when I press "refresh models" they all show up but no matter which one I choose I get that error.  

I have turned on Debugging but I am unsure where to look for the logs to dig deeper.  

I am familiar with azure model deployments which has it's own quirks compared to the standard openai api so if you need help with testing I am willing to help.

**Comment by chasebank87** [comment]
Yes, thank you. This is a known issue right now. Haven’t had the time to get Microsoft, anthropic, and Google built out yet.Sent from my iPhoneOn Sep 24, 2024, at 2:57 PM, wally-kroeker ***@***.***> wrote:﻿
I am actively using Azure models with other projects, including in production at my work so I know the deployment is setup right.
When I try it with mesh-ai it fails with the error below.
Error: LLM Request failed: Failed to generate
response: net::ERR_NAME_NOT_RESOLVED
I have a number of models under the same azure endpoint and when I press "refresh models" they all show up but no matter which one I choose I get that error.
I have turned on Debugging but I am unsure where to look for the logs to dig deeper.
I am familiar with azure model deployments which has it's own quirks compared to the standard openai api so if you need help with testing I am willing to help.
