### ISSUE TITLE
Plugin not working in Obsidian

### ISSUE THREAD

**Issue by poezie** [chasebank87/mesh-ai#19]
I have installed the Mesh-AI plugin but when I try use it all I see when I click the brain icon is a box I can choose the LLM engine. I have tried to use Ollama and Groq , which I can select but there are no other options on the page it opens , any idea as in the videos I should be able to select other variables

**Comment by poezie** [comment]
![Screenshot 2024-09-26 at 12 16 54 AM](https://github.com/user-attachments/assets/4d3a4283-89a9-4dd5-a6e4-c11cbf24f44e)

**Comment by poezie** [comment]
Sorry also using default Theme

**Comment by chasebank87** [comment]
Do me a favor and try to install the borders theme, And tell me if that fixes it. This will help me identify the issue, I developed the plugin with the borders theme active, and this is the first report of this issue.If a theme fixes it I will track down the problem from there.Sent from my iPhoneOn Sep 25, 2024, at 10:20 AM, poezie ***@***.***> wrote:﻿
Sorry also using default Theme

**Comment by chasebank87** [comment]
Is it possible you have any custom css snipets?

**Comment by poezie** [comment]
I tried border theme and the issue stays. 

I am not aware of any custom CSS snipets

I did have the old Fabric unoffical plugin installed but I have disabled this for now

**Comment by chasebank87** [comment]
This is very weird, I can’t duplicate the issue on my end. Can you try disabling all the plugins that you have except for mesh.. maybe reinstall obsidian..Sent from my iPhoneOn Sep 26, 2024, at 1:30 AM, poezie ***@***.***> wrote:﻿
I tried border theme and the issue stays.
I am not aware of any custom CSS snipets
I did have the old Fabric unoffical plugin installed but I have disabled this for now

**Comment by poezie** [comment]
I disabled all te plugins and left the Mesh-AI but the interface looks the same. 

I am on a Mac OSX system so not sure if that makes any difference ?

**Comment by chasebank87** [comment]
I’m on Mac to, this is very strange.Sent from my iPhoneOn Sep 26, 2024, at 6:09 AM, poezie ***@***.***> wrote:﻿
I disabled all te plugins and left the Mesh-AI but the interface looks the same.
I am on a Mac OSX system so not sure if that makes any difference ?

**Comment by poezie** [comment]
I can turn on debugging but need to know where I can find logs for you ? I am not sure where to look . I have now uninstalled the old unofficial fabric and MeshAi, reinstalled MeshAi but the interface  is still as shown above in the screen shot. Is there anything I can send you that might indicate why the other boxes are not presenting in the gui ?

**Comment by chasebank87** [comment]
When you enable debugging it adds additional logs in the web developer tools from the view menu, specifically on the console tab.However this issue being styling I don’t think that’s going to help but we can see.Also the interface is correct they are just stacked on top of each other. Sent from my iPhoneOn Sep 26, 2024, at 9:10 PM, poezie ***@***.***> wrote:﻿
I can turn on debugging but need to know where I can find logs for you ? I am not sure where to look . I have now uninstalled the old unofficial fabric and MeshAi, reinstalled MeshAi but the interface  is still as shown above in the screen shot. Is there anything I can send you that might indicate why the other boxes are not presenting in the gui ?

**Comment by poezie** [comment]
I have tested a fresh install of obsidian , and only enabled he MeshAI plugin , the UI has the same issue I presented above so this happened on a clean install as well

**Comment by chasebank87** [comment]
I figured it out,Let me guess, you haven’t setup the settings in the plugin settings? Do me a favor go through the plugin settings and fill in everything pertinent to you.Sent from my iPhoneOn Sep 26, 2024, at 9:20 PM, poezie ***@***.***> wrote:﻿
I have tested a fresh install of obsidian , and only enabled he MeshAI plugin , the UI has the same issue I presented above so this happened on a clean install as well

**Comment by poezie** [comment]
I have setup the Ollama and the Groq settings , I can even choose the model to use ....am I missing something else ?

**Comment by chasebank87** [comment]
After you set the api key you should be able to refresh the models, also you need to set the pattern folders.Sent from my iPhoneOn Sep 27, 2024, at 1:08 AM, poezie ***@***.***> wrote:﻿
I have setup the Ollama and the Groq settings , I can even choose the model to use ....am I missing something else ?

**Comment by poezie** [comment]
I have done all this Sent from my iPhoneOn 27 Sep 2024, at 15:10, Chase Elder ***@***.***> wrote:﻿
After you set the api key you should be able to refresh the models, also you need to set the pattern folders.Sent from my iPhoneOn Sep 27, 2024, at 1:08 AM, poezie ***@***.***> wrote:﻿

I have setup the Ollama and the Groq settings , I can even choose the model to use ....am I missing something else ?

**Comment by chasebank87** [comment]
Okay we finally found the issue. There is a bug that OpenAI api key is required to get it to work. I’ll look into why that is but for now you can enter a key there and it should work.Sent from my iPhoneOn Sep 27, 2024, at 1:12 AM, poezie ***@***.***> wrote:﻿
I have done all this Sent from my iPhoneOn 27 Sep 2024, at 15:10, Chase Elder ***@***.***> wrote:﻿

After you set the api key you should be able to refresh the models, also you need to set the pattern folders.Sent from my iPhoneOn Sep 27, 2024, at 1:08 AM, poezie ***@***.***> wrote:﻿



I have setup the Ollama and the Groq settings , I can even choose the model to use ....am I missing something else ?

**Comment by poezie** [comment]
Perfect , once I added a OpenAI key the UI is resolved

Thanks
