### ISSUE TITLE
Only OpenAI Funtional

### ISSUE THREAD

**Issue by syhr** [chasebank87/mesh-ai#2]
This is great and works really well for me, except it won't load any other models except for OpenAI. I've generated all new keys for Gemini and Anthropic, and it just won't load any models. Groq works fine. I wasn't sure if this was known or if it was just me. I know you're just getting this together. Let me know what you need from me: the latest version of Obsidian and the latest version of your plug-in.

**Comment by chasebank87** [comment]
Sorry I have not gotten anthropic, Google, and Microsoft working fully. Should be added in the next week or so.Sent from my iPhoneOn Sep 5, 2024, at 1:15 PM, syhr ***@***.***> wrote:﻿
This is great and works really well for me, except it won't load any other models except for OpenAI. I've generated all new keys for Gemini and Anthropic, and it just won't load any models. Groq works fine. I wasn't sure if this was known or if it was just me. I know you're just getting this together. Let me know what you need from me: the latest version of Obsidian and the latest version of your plug-in.

**Comment by syhr** [comment]
No problem at all, and again, much appreciated. I will close this out and keep tabs on the releases.
