### ISSUE TITLE
Google Models Not showing after refresh button pushed. 

### ISSUE THREAD

**Issue by grizzlycode** [chasebank87/mesh-ai#20]
Issue: 

I've entered my Gemini API key and selected the "Refresh models" button, but it doesn't produce a list of models. I have tested this key and it works with other apps.

**Comment by chasebank87** [comment]
Gemini is not supported yet as mentioned in the read me. Currently the only supported providers are, OpenAI, openrouter , grocq and ollama Sent from my iPhoneOn Sep 26, 2024, at 12:55 PM, grizzlycode ***@***.***> wrote:﻿
Issue:
I've entered my Gemini API key and selected the "Refresh models" button, but it doesn't produce a list of models. I have tested this key and it works with other apps.

**Comment by grizzlycode** [comment]
My bad, I guess I missed that. I'll close this out then since its not yet supported.
