### ISSUE TITLE
LM Studio as local llm setup ?

### ISSUE THREAD

**Issue by userchet** [chasebank87/mesh-ai#22]
I am currently using LM Studio (local llm) with Fabric 2.0

Fabric works well, the problem is the setup of mesh ai plugin as i cannot use any url with openai (lm studio use a ssystem like openai) like i did with fabric.

To make it work I think I would need to have a specific url (my local one) to use with Openai API key.

Any idea or way I could solve that ?

Thx for your time and help !

**Comment by chasebank87** [comment]
New version is out with lm studio
