### ISSUE TITLE
ERROR: LLM Request Failed

### ISSUE THREAD

**Issue by Beingpax** [chasebank87/mesh-ai#24]
![CleanShot 2024-10-02 at 20 55 20](https://github.com/user-attachments/assets/431b61ed-a507-4569-a21e-01d01b1b2eb4)

Its working when copying content. But when I copy the youtube link, it shows this error. 

Also the UI is not visible. 

![CleanShot 2024-10-02 at 21 00 22](https://github.com/user-attachments/assets/ea462e79-76d5-430e-86e0-b66693113d83)

Only shows this section. Nothing else to configure.

**Comment by Beingpax** [comment]
I'm running on 1.2.1 
still not resolved. 
![CleanShot 2024-10-02 at 21 12 49](https://github.com/user-attachments/assets/8e2466ab-e812-4904-8f8a-1b33f017fd61)

**Comment by chasebank87** [comment]
Change your default provider in settings.Sent from my iPhoneOn Oct 2, 2024, at 11:29 AM, Beingpax ***@***.***> wrote:﻿
I'm running on 1.2.1
still not resolved.
CleanShot.2024-10-02.at.21.12.49.gif (view on web)

**Comment by Beingpax** [comment]
Oh, how stupid I was not not see that. Thanks
