### ISSUE TITLE
Provider Default in UI

### ISSUE THREAD

**Issue by rudijs** [chasebank87/mesh-ai#5]
Hi, I'm using this plugin on Ubuntu Linux w/ Obsidian V1.6.7

Each time I open the plugin in the UI it forgets the previous settings, so I have to reset them each time.

I want it to default to grocq, but it opens with openai each time.

Should it work this way or can we have the previous settings remembered for next use?

**Comment by chasebank87** [comment]
Im going to close this out, but you can use the version 1.0.5 (this version im using for post release changes) this version will give you all the features ive added and issues ive fixed recently.
