### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by rudijs** [chasebank87/mesh-ai#6]
Hi,

Some YT urls are not happy.

This one for example: https://youtu.be/ahMRdZ7KnTM?si=LihvNZnzIbji2-IV

```
yt 'https://youtu.be/ahMRdZ7KnTM?si=LihvNZnzIbji2-IV' | fabric -sp extract_wisdom
panic: runtime error: index out of range [0] with length 0

goroutine 21 [running]:
github.com/danielmiessler/fabric/vendors/openai.(*Client).SendStream(0xc000127200, {0xc00041e5c0?, 0x0?, 0x0?}, 0x0?, 0xc000112700)
        /home/rudi/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.3/vendors/openai/openai.go:78 +0x475
github.com/danielmiessler/fabric/core.(*Chatter).Send.func1()
        /home/rudi/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.3/core/chatter.go:37 +0x3d
created by github.com/danielmiessler/fabric/core.(*Chatter).Send in goroutine 1
        /home/rudi/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.3/core/chatter.go:36 +0x149
```

It's working great most of the time, sometimes it blows not (not sure how to debug Go lang)

**Comment by chasebank87** [comment]
This is an issue I would definitely post on the fabric GitHub, I did base my YouTube transcription on his same method but ported over to typescript. For mesh-ai though we do not use any fabric binaries or libraries.Sent from my iPhoneOn Sep 13, 2024, at 2:44 AM, Rudi Starcevic ***@***.***> wrote:﻿
Hi,
Some YT urls are not happy.
This one for example: https://youtu.be/ahMRdZ7KnTM?si=LihvNZnzIbji2-IV
yt 'https://youtu.be/ahMRdZ7KnTM?si=LihvNZnzIbji2-IV' | fabric -sp extract_wisdom
panic: runtime error: index out of range [0] with length 0

goroutine 21 [running]:
github.com/danielmiessler/fabric/vendors/openai.(*Client).SendStream(0xc000127200, {0xc00041e5c0?, 0x0?, 0x0?}, 0x0?, 0xc000112700)
        ***@***.***/vendors/openai/openai.go:78 +0x475
github.com/danielmiessler/fabric/core.(*Chatter).Send.func1()
        ***@***.***/core/chatter.go:37 +0x3d
created by github.com/danielmiessler/fabric/core.(*Chatter).Send in goroutine 1
        ***@***.***/core/chatter.go:36 +0x149

It's working great most of the time, sometimes it blows not (not sure how to debug Go lang)
