### ISSUE TITLE
Sliders displaced in graph view settings

### ISSUE THREAD

**Issue by beyaro8om** [chasebank87/mesh-ai#8]
![](https://i.imgur.com/6S77gAY.png)

**Comment by chasebank87** [comment]
Thanks! I’ll get that fixed and let ya know.Sent from my iPhoneOn Sep 14, 2024, at 10:01 AM, beyaro8om ***@***.***> wrote:﻿

**Comment by chasebank87** [comment]
Hey! I resolved the bug you found. For now the updates im pushing are all going to be to version 1.0.5. Be sure to use that version until Obsidian approves the plugin officially. 

There are a lot of new features like custom workflows found in the settings pane. Would love if you could keep testing things out.  Thank for your input!
